name: Main Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout Meadow.Project.Samples
      uses: actions/checkout@v3
      with:
        path: Meadow.Project.Samples
        ref: main

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources

    - name: Install MAUI Android Workload
      run: dotnet workload install maui-android --ignore-failed-sources
      
    - name: Build Meadow.Project.Samples
      run: dotnet build -c Release Meadow.Project.Samples/Source/Meadow.Project.Samples.sln